// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for RunningScheduleFunction
 */
export interface RunningScheduleFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/funcs/running-schedule.
 */
export class RunningScheduleFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: RunningScheduleFunctionProps) {
    super(scope, id, {
      description: 'src/funcs/running-schedule.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs24.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/funcs/running-schedule.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}